Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,6 +45,16 @@ jobs:
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx  # Adjust path if needed
        continue-on-error: true
+
+     - name: RunL inting
+       run: npm run lint -- --format=json > reports/lint.json || true  # Redirect output to JSON file, continue on error
+
+     - name: Upload Linting Report
+       if: success() || failure()  # Proceed regardless of linting outcome
+       uses: actions/upload-artifact@v2
+       with:
+         name: lint-report
+         path: reports/lint.json
        
 #jest test is used for jaavaScript Testing Framework with a focus on simplicity.
   jest-test:
